#!/bin/sh

intercept_ssh() {
	uci -q delete firewall.ssh_int
	uci set firewall.ssh_int="redirect"
	uci set firewall.ssh_int.name="Intercept-SSH"
	uci set firewall.ssh_int.src="lan"
	uci set firewall.ssh_int.src_dport="22"
	uci set firewall.ssh_int.proto="tcp"
	uci set firewall.ssh_int.target="DNAT"
}

intercept_http() {
	uci -q delete firewall.http_int
	uci set firewall.http_int="redirect"
	uci set firewall.http_int.name="Intercept-HTTP"
	uci set firewall.http_int.src="lan"
	uci set firewall.http_int.src_dport="8080"
	uci set firewall.http_int.proto="tcp"
	uci set firewall.http_int.target="DNAT"
}

intercept_https() {
	uci -q delete firewall.https_int
	uci set firewall.https_int="redirect"
	uci set firewall.https_int.name="Intercept-HTTPS"
	uci set firewall.https_int.src="lan"
	uci set firewall.https_int.src_dport="8443"
	uci set firewall.https_int.proto="tcp"
	uci set firewall.https_int.target="DNAT"
}

intercept_dns() {
	uci -q delete firewall.dns_int
	uci set firewall.dns_int="redirect"
	uci set firewall.dns_int.name="Intercept-DNS"
	uci set firewall.dns_int.src="lan"
	uci set firewall.dns_int.src_dport="53"
	uci set firewall.dns_int.dest_port="9053"
	uci set firewall.dns_int.proto="udp"
	uci set firewall.dns_int.target="DNAT"
}

intercept_tcp() {
	uci -q delete firewall.tcp_int
	uci set firewall.tcp_int="redirect"
	uci set firewall.tcp_int.name="Intercept-TCP"
	uci set firewall.tcp_int.src="lan"
	uci set firewall.tcp_int.dest_port="9040"
	uci set firewall.tcp_int.proto="tcp"
	uci set firewall.tcp_int.extra="--syn"
	uci set firewall.tcp_int.target="DNAT"
}

disable_lan_wan_forwarding() {
	uci set firewall.@forwarding[0].enabled="0"
}

enable_nat6() {
	cat > /etc/firewall.nat6 <<- EOF
		iptables-save -t nat \
| sed -e "/\s[DS]NAT\s/d;/\sMASQUERADE$/d" \
| ip6tables-restore -T nat
	EOF

	uci -q delete firewall.nat6
	uci set firewall.nat6="include"
	uci set firewall.nat6.path="/etc/firewall.nat6"
	uci set firewall.nat6.reload="1"
}

intercept_ssh
intercept_http
intercept_https
intercept_dns
intercept_tcp
disable_lan_wan_forwarding
enable_nat6

uci commit firewall
/etc/init.d/firewall restart
