#!/bin/sh

check_daemon() {
	daemon_PID=$(ps | pgrep -o -f "/bin/sh /sbin/project_daemon")

	if [ ! ${daemon_PID} ]; then
		(/sbin/project_daemon)&	# Start project_persistency in a subshell and put it in the background
		daemon_PID=$(ps | pgrep -o -f "/bin/sh /sbin/project_daemon")

		cat > /usr/PROJECT/daemon.pid <<- EOM	# Write the PID of /bin/sh /sbin/project_persistency
			${daemon_PID}
		EOM
	fi
}


while true; do
	check_daemon
done
